### ISSUE TITLE
"invalid SDP" while connecting to IP-camera

### ISSUE THREAD

**Issue by WGOS** [aler9/rtsp-simple-proxy#7]
Greetings.

I'm trying to proxy my IP camera's RTSP stream and getting following error:
```
2020/06/15 21:35:57 [STREAM cam1] initializing with protocol udp
2020/06/15 21:35:57 [STREAM cam1] ERR: invalid SDP: decode failed: field origin is unexpected: DecodeError in section s: no matches in ordering array at s[2] for origin
```

Here's the conf.yml
```yaml
server:
  protocols: [ tcp, udp ]

streams:
  cam1:
    url: rtsp://viewer:somepassword@192.168.8.210:554/channel1
    protocol: tcp
```

IP-Cam model: **rvi-ipc50dn12**
